In [ ]:
!pip install pandas
import pandas as pd
pd.__version__

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.22.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

'1.5.3'

In [ ]:
import numpy as np
np.__version__

'1.22.4'

Numpy
1 Dimensao -> vetores
2 Dimensoes -> matriz

Pandas
1 Dimensao -> series
2 Dimensoes -> DataFrame

In [ ]:
lista = [1,2,3,4,5]
serie = pd.Series(lista)
serie

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
type(serie.values)

numpy.ndarray

In [ ]:
serie.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
serie.dtype

dtype('int64')

In [ ]:
serie.astype(str).values

array(['1', '2', '3', '4', '5'], dtype=object)

In [ ]:
serie

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
serie * 2

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [ ]:
lista = [
    'maisena',
    'farinha',
    'açucar',
    'ovos',
    'manteiga',
    'castanha'
]
ingredientes = pd.Series(lista, name='ingredientes')
ingredientes

0     maisena
1     farinha
2      açucar
3        ovos
4    manteiga
5    castanha
Name: ingredientes, dtype: object

In [ ]:
dados = [200, 250, 100, 2, 150, 180]
indice = ingredientes.copy()
qtd = pd.Series(data=dados, index=indice, name='quantidade')
qtd

ingredientes
maisena     200
farinha     250
açucar      100
ovos          2
manteiga    150
castanha    180
Name: quantidade, dtype: int64

In [ ]:
df = pd.DataFrame(data={
    "ingredientes": ingredientes,
    "qtd": qtd.values
})
df

  ingredientes  qtd
0      maisena  200
1      farinha  250
2       açucar  100
3         ovos    2
4     manteiga  150
5     castanha  180

In [ ]:
df.values

array([['maisena', 200],
       ['farinha', 250],
       ['açucar', 100],
       ['ovos', 2],
       ['manteiga', 150],
       ['castanha', 180]], dtype=object)

In [ ]:
df.to_dict()

{'ingredientes': {0: 'maisena',
  1: 'farinha',
  2: 'açucar',
  3: 'ovos',
  4: 'manteiga',
  5: 'castanha'},
 'qtd': {0: 200, 1: 250, 2: 100, 3: 2, 4: 150, 5: 180}}

In [ ]:
df.columns

Index(['ingredientes', 'qtd'], dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [ ]:
df.dtypes

ingredientes    object
qtd              int64
dtype: object

In [ ]:
df['ingredientes']

0     maisena
1     farinha
2      açucar
3        ovos
4    manteiga
5    castanha
Name: ingredientes, dtype: object

In [ ]:
df['qtd']

0    200
1    250
2    100
3      2
4    150
5    180
Name: qtd, dtype: int64

In [ ]:
df

  ingredientes  qtd
0      maisena  200
1      farinha  250
2       açucar  100
3         ovos    2
4     manteiga  150
5     castanha  180

In [ ]:
df.head(3)

  ingredientes  qtd
0      maisena  200
1      farinha  250
2       açucar  100

In [ ]:
df.tail(3)

  ingredientes  qtd
3         ovos    2
4     manteiga  150
5     castanha  180

In [ ]:
df.loc[2:4, :]#linhas, colunas

  ingredientes  qtd
2       açucar  100
3         ovos    2
4     manteiga  150

In [ ]:
df.index = ['ingrediente1','ingrediente2', 'ingrediente3', 'ingrediente4', 'ingrediente5', 'ingrediente6']
df

             ingredientes  qtd
ingrediente1      maisena  200
ingrediente2      farinha  250
ingrediente3       açucar  100
ingrediente4         ovos    2
ingrediente5     manteiga  150
ingrediente6     castanha  180

In [ ]:
df.loc['ingrediente2':'ingrediente4','ingrediente':'qtd']

             ingredientes  qtd
ingrediente2      farinha  250
ingrediente3       açucar  100
ingrediente4         ovos    2

In [ ]:
df.loc[['ingrediente5','ingrediente4','ingrediente1'],'ingrediente':'qtd']

             ingredientes  qtd
ingrediente5     manteiga  150
ingrediente4         ovos    2
ingrediente1      maisena  200

In [ ]:
df

             ingredientes  qtd
ingrediente1      maisena  200
ingrediente2      farinha  250
ingrediente3       açucar  100
ingrediente4         ovos    2
ingrediente5     manteiga  150
ingrediente6     castanha  180

In [ ]:
df.iloc[2:5, :]

             ingredientes  qtd
ingrediente3       açucar  100
ingrediente4         ovos    2
ingrediente5     manteiga  150

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, ingrediente1 to ingrediente6
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ingredientes  6 non-null      object
 1   qtd           6 non-null      int64
dtypes: int64(1), object(1)
memory usage: 316.0+ bytes

In [ ]:
df.describe()

              qtd
count    6.000000
mean   147.000000
std     86.890736
min      2.000000
25%    112.500000
50%    165.000000
75%    195.000000
max    250.000000

In [ ]:
df.describe(include='all')

       ingredientes         qtd
count             6    6.000000
unique            6         NaN
top         maisena         NaN
freq              1         NaN
mean            NaN  147.000000
std             NaN   86.890736
min             NaN    2.000000
25%             NaN  112.500000
50%             NaN  165.000000
75%             NaN  195.000000
max             NaN  250.000000

In [ ]:
df.sort_values('qtd')

             ingredientes  qtd
ingrediente4         ovos    2
ingrediente3       açucar  100
ingrediente5     manteiga  150
ingrediente6     castanha  180
ingrediente1      maisena  200
ingrediente2      farinha  250

In [ ]:
df.sort_values('qtd', ascending=False)

             ingredientes  qtd
ingrediente2      farinha  250
ingrediente1      maisena  200
ingrediente6     castanha  180
ingrediente5     manteiga  150
ingrediente3       açucar  100
ingrediente4         ovos    2

In [ ]:
e_farinha = df['ingredientes'] == 'farinha'
e_farinha

ingrediente1    False
ingrediente2     True
ingrediente3    False
ingrediente4    False
ingrediente5    False
ingrediente6    False
Name: ingredientes, dtype: bool

In [ ]:
df[e_farinha]

             ingredientes  qtd
ingrediente2      farinha  250

In [ ]:
mi_200 = df['qtd'] <= 200
mi_200

ingrediente1     True
ingrediente2    False
ingrediente3     True
ingrediente4     True
ingrediente5     True
ingrediente6     True
Name: qtd, dtype: bool

In [ ]:
df[mi_200]

             ingredientes  qtd
ingrediente1      maisena  200
ingrediente3       açucar  100
ingrediente4         ovos    2
ingrediente5     manteiga  150
ingrediente6     castanha  180

In [ ]:
lista_especial = ['castanha','manteiga','leite','pão','farinha']
dentro_le = df['ingredientes'].isin(lista_especial)
df[dentro_le]

             ingredientes  qtd
ingrediente5     manteiga  150
ingrediente6     castanha  180

In [ ]:
filtro = dentro_le & mi_200
df[filtro]

             ingredientes  qtd
ingrediente5     manteiga  150
ingrediente6     castanha  180

In [ ]:
filtro = dentro_le | mi_200
df[filtro]

             ingredientes  qtd
ingrediente1      maisena  200
ingrediente3       açucar  100
ingrediente4         ovos    2
ingrediente5     manteiga  150
ingrediente6     castanha  180

In [ ]:
~dentro_le
df[~dentro_le]

             ingredientes  qtd
ingrediente1      maisena  200
ingrediente2      farinha  250
ingrediente3       açucar  100
ingrediente4         ovos    2